export const TOGGLE_HAS_LOGIN_ERRORS = "TOGGLE_HAS_LOGIN_ERRORS";
export const TOGGLE_IS_LOGGING_IN = "TOGGLE__IS_LOGGING_IN";
export const IS_USER_FETCHING = "IS_USER_FETCHING";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_TOKEN = "SET_TOKEN";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const SET_LOGIN_ERRORS = "SET_LOGIN_ERRORS";
export const SET_LOGIN_MODE = "SET_LOGIN_MODE";

export const TOGGLE_USER_FOLLOWEES = "TOGGLE_USER_FOLLOWEES";
export const TOGGLE_PUBLICATION_RELEASES_READ = "TOGGLE_PUBLICATION_RELEASES_READ";
export const SET_USER_PUBLICATION_RELEASE = "SET_USER_PUBLICATION_RELEASE";
