export const TOGGLE_MAGAZINES_LOADING = "TOGGLE_MAGAZINES_LOADING";
export const TOGGLE_MAGAZINES_PUBLICATION_RELEASES_LOADING =
  "TOGGLE_MAGAZINES_PUBLICATION_RELEASES_LOADING";
export const TOGGLE_MAGAZINE_PUBLICATION_RELEASE_LOADING =
  "TOGGLE_MAGAZINE_PUBLICATION_RELEASE_LOADING";
export const SET_MAGAZINES = "SET_MAGAZINES";
export const SET_MAGAZINE = "SET_MAGAZINE";
export const SET_MAGAZINE_PUBLICATION_RELEASES = "SET_MAGAZINE_PUBLICATION_RELEASES";
export const SET_MAGAZINE_PUBLICATION_RELEASE = "SET_MAGAZINE_PUBLICATION_RELEASE";
