export const TOGGLE_ARTICLE_LIST_LOADING = "TOGGLE_ARTICLE_LIST_LOADING";
export const TOGGLE_ARTICLE_LOADING = "TOGGLE_ARTICLE_LOADING";
export const SET_ARTICLE_LIST = "SET_ARTICLE_LIST";
export const SET_MAGAZINE_ARTICLES = "SET_MAGAZINE_ARTICLES";
export const SET_ARTICLE = "SET_ARTICLE";
