export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const TOGGLE_NOTIFICATIONS_LOADING = "TOGGLE_NOTIFICATIONS_LOADING";
export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
