export const SET_PODCASTS = "SET_PODCASTS";
export const SET_LATEST_PODCAST = "SET_LATEST_PODCAST";
export const TOGGLE_PODCASTS_LOADING = "TOGGLE_PODCASTS_LOADING";
export const TOGGLE_PODCAST_LOADING = "TOGGLE_PODCAST_LOADING";
