export const SET_PODCASTS = "SET_PODCASTS";
export const SET_PODCAST = "SET_PODCAST";
export const SET_LATEST_PODCAST = "SET_LATEST_PODCAST";
export const TOGGLE_PODCASTS_LOADING = "TOGGLE_PODCASTS_LOADING";
export const TOGGLE_PODCAST_LOADING = "TOGGLE_PODCAST_LOADING";
export const SET_NOW_PLAYING_SOUND_OBJECT = "SET_NOW_PLAYING_SOUND_OBJECT";
export const SET_NOW_PLAYING_PLAY_BACK_STATUS = "SET_NOW_PLAYING_PLAY_BACK_STATUS";
export const SET_NOW_PLAYING = "SET_NOW_PLAYING";
