export const TOGGLE_POST_LIST_LOADING = "TOOGLE_POST_LIST_LOADING";
export const TOGGLE_POST_LOADING = "TOGGLE_POST_LOADING";
export const SET_POST_LIST = "SET_POST_LIST";
export const SET_POST = "SET_POST";