export const SET_USER = "SET_USER";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_CURRENT_USER_FOLLOWERS = "SET_CURRENT_USER_FOLLOWERS";
export const TOGGLE_CURRENT_USER_FOLLOWERS_LOADING = "TOGGLE_CURRENT_USER_FOLLOWERS_LOADING";
export const SET_CURRENT_USER_FOLLOWEES = "SET_CURRENT_USER_FOLLOWEES";
export const TOGGLE_CURRENT_USER_FOLLOWEES_LOADING = "TOGGLE_CURRENT_USER_FOLLOWEES_LOADING";
export const TOGGLE_USERS_LOADING = "TOGGLE_USERS_LOADING";
export const SET_USERS = "SET_USERS";
